### ISSUE TITLE
dns detail not updated with combo box

### ISSUE THREAD

**Issue by Mahdiali313** [mrmoein/GUI-DNS-changer-for-linux#1]
hello
after remove google public dns , "dns server" name in combo box not sync with below detail.
thank you
![Screenshot from 2022-04-27 17-57-26](https://user-images.githubusercontent.com/52355596/165531928-c77fd0c6-d705-40fb-ab8d-8222ef404413.png)

**Comment by mrmoein** [comment]
Hi, I confirm the problem and I fixed it.
Check the latest commit
